//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Recommendation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedIE
    {
        public int ApproveID { get; set; }
        public int CompanyID { get; set; }
        public int Parameter1 { get; set; }
        public int Parameter2 { get; set; }
        public int Parameter3 { get; set; }
        public int Parameter4 { get; set; }
        public int Parameter5 { get; set; }
        public int Parameter6 { get; set; }
        public int Parameter7 { get; set; }
        public int Parameter8 { get; set; }
        public int Parameter9 { get; set; }
        public int Parameter10 { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> UniID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> UniYearID { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> AgeID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> InternshipPeriod { get; set; }
    }
}
