//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Recommendation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectedPeriod
    {
        public int ExpectedPeriodID { get; set; }
        public string PeriodDescription { get; set; }
    }
}
