//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Recommendation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternshipExperience
    {
        public int ExpID { get; set; }
        public int CompanyID_FK { get; set; }
        public int JobID_FK { get; set; }
        public System.DateTime YearStarted { get; set; }
        public int UniversityYear_FK { get; set; }
        public int InternshipPeriod { get; set; }
        public bool IsCompleted { get; set; }
        public string AcceptanceLetterPath { get; set; }
        public string ServiceLetterPath { get; set; }
        public int Parameter1 { get; set; }
        public int Parameter2 { get; set; }
        public int Parameter3 { get; set; }
        public int Parameter4 { get; set; }
        public int Parameter5 { get; set; }
        public int Parameter6 { get; set; }
        public int Parameter7 { get; set; }
        public int Parameter8 { get; set; }
        public int Parameter9 { get; set; }
        public int Parameter10 { get; set; }
        public bool IsApproved { get; set; }
        public int StudentID_FK { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Job Job { get; set; }
        public virtual Student Student { get; set; }
        public virtual UniYear UniYear { get; set; }
    }
}
