//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Recommendation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniYear()
        {
            this.InternshipExperiences = new HashSet<InternshipExperience>();
        }
    
        public int UniYearID { get; set; }
        public string UniYearVal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternshipExperience> InternshipExperiences { get; set; }
    }
}
